services:
  server:
    image: fauria/vsftpd
    ports:
      - 2121:21
    environment:
      - "FTP_USER=${FTP_USER}"
      - "FTP_PASS=${FTP_PASS}"
      - "PASV_ADDRESS=server"
      - "PASV_ADDR_RESOLVE=YES"
    volumes:
      - server-data:/home/vsftpd/
    networks:
      - net
      
  client:
    image: lscr.io/linuxserver/filezilla:latest
    volumes:
      - client-config:/config
    ports:
      - 3001:3001
    networks:
      - net

  wireshark:
    image: lscr.io/linuxserver/wireshark:latest
    environment:
      - TZ=Europe/Paris
    volumes:
      - wireshark-config:/config
    ports:
      - 3002:3001
    cap_add:
      - NET_ADMIN
    shm_size: "1gb"
    restart: unless-stopped
    profiles: ["tools"]
    networks:
      - net

  inquisitor:
    image: inquisitor
    build:
      context: .
      dockerfile: rsc/docker/Dockerfile
    profiles: ["prod"]
    networks:
      - net
    
volumes:
  server-data:
  client-config:
  wireshark-config:

networks:
  net: